### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by realdadfish** [jenkinsci/code-coverage-api-plugin#111]
First off, I'm very thankful that the issue of coverage diff metrics gets finally tackled for Jenkins, thanks a bunch for stepping up!
When I read the announcement over on jenkins.io a few questions popped up in my mind:

1. The plugin only seems to cover lines as smallest "thing", but not instructions, like tools e.g. JaCoCo support. Especially in complex business logic it is very much needed to see if not only one branch of an if statement is executed, but both. Is there a reason why this is left out?
2. In multi-module Java / Kotlin projects there is usually more than a single JaCoCo coverage file falling out at the end. Is this supported by this plugin or is the user of the plugin forced to merge (with JaCoCo's Gradle / Maven / Ant tooling) single `.ec` coverage files before, create an XML report out of that and then feed it into the plugin?
3. We came up with our own violations check machinery for PRs where we basically define a threshold (minimum coverage) for each module +/- 2% coverage, so a developer needs to adapt this configured threshold when he raises it (so a new "better" baseline is applied). On the other side, if the value is lowered by the developer, it can be seen in the PR and then argued about. I understand that the configuration you can do with the plugin currently basically is used for a lower-boundary check, would an upper-boundary check be possible as well in this regard?
4. Finally, what I miss the most about my current machinery is the inability to drill into specific coverage changes. I'd like to see in which modules / packages / classes I lost coverage (because of added code or removed / rewritten tests). External tools like codecov.io have the ability to present this nicely - is support for such a feature planned as well?

Thanks in advance!

**Comment by cizezsy** [comment]
@realdadfish 
 > 1. The plugin only seems to cover lines as smallest "thing", but not instructions like tools e.g. JaCoCo support.

This plugin actually supports 'Instruction' metric if you are using JaCoCo adapter to collect coverage report. But it can only show how many instructions covered and uncovered now. 
> it is very much needed to see if not only one branch of an if statement is executed, but both.

It also supports 'Conditional' metric so that you can see whether a branch of an if statement covered in Source File Navigation view(How to enter to source file navigation https://github.com/jenkinsci/code-coverage-api-plugin/issues/74)

> 2. In multi-module Java / Kotlin projects there is usually more than a single JaCoCo coverage file falling out at the end. Is this supported by this plugin or is the user of the plugin forced to merge (with JaCoCo's Gradle / Maven / Ant tooling) single .ec coverage files before, create an XML report out of that and then feed it into the plugin?

Yes, this plugin supports multiple reports, it will read all those reports and aggregates them. If you want to merge those reports into one, you can use `mergeToOneReport` option, so that all reports found by adapter will be merged.

usage:
```groovy
publishCoverage adapters: [jacocoAdapter(mergeToOneReport: true, path: '**/*.xml')]
```

> 3. We came up with our own violations check machinery for PRs where we basically define a threshold (minimum coverage) for each module +/- 2% coverage, so a developer needs to adapt this configured threshold when he raises it (so a new "better" baseline is applied). On the other side, if the value is lowered by the developer, it can be seen in the PR and then argued about. I understand that the configuration you can do with the plugin currently basically is used for a lower-boundary check, would an upper-boundary check be possible as well in this regard?

This is a really good idea, will add it in the future :)

> 4. finally, what I miss the most about my current machinery is the inability to drill into specific coverage changes...
Yes, will add it in the future too :P


Thanks very much for your suggestion!  Those features are really useful. once I have time, I will implement them into this plugin.
