### ISSUE TITLE
Ignore class files that do not contain code from JaCoCo reports

### ISSUE THREAD

**Issue by nbarithel** [jenkinsci/code-coverage-api-plugin#127]
Hi, 

Currently, Class files, **mainly abstract class or interfaces** (without default methods), that do not contain code are shown with a 0/1 coverage in Jenkins reports based on JaCoCo.
In fact, **File** and **Class** Category display a result of 0%, whereas **Method**, **Instruction**, **Line**, **Conditional** display a blank result which is fine:
![coverage-interface](https://user-images.githubusercontent.com/3244695/66753211-9772d800-ee93-11e9-9048-b80ec1e7971d.png)

Is this something that can be fixed ?

Regards

Nicolas

**Comment by DJViking** [comment]
Is it a bug, or is it supposed to report 0%?

We are seeing this also for interfaces, enums, and our custom Exception classes.

![Screenshot_20200310_131114](https://user-images.githubusercontent.com/3070076/76311225-bf465a80-62d0-11ea-9c03-44227266d471.png)

We have one interface here shown in the screenshot that has coverage on Method, Instructions, Line. That is because that interface has an inner enum and a default method.

Does these 0% coverages impact the overall coverage percentage? Looking at "Divided by Package Name" the package that contains all my listeners do impact overall coverage. It should be 100% for these.
![Screenshot_20200310_131442](https://user-images.githubusercontent.com/3070076/76311422-3380fe00-62d1-11ea-81c7-8a889d0bd528.png)

Empty I surmise that they are N/A, I.E. the class does not contain any branches to cover (no if-else, switch, for/while loops).

**Comment by uhafner** [comment]
This view is not available anymore.
