### ISSUE TITLE
Painting the coverage results takes a long time

### ISSUE THREAD

**Issue by edmeme** [jenkinsci/code-coverage-api-plugin#155]
For large projects, most of the time is not spent on testing, but on painting the source files to display line coverage. This can be rather extreme, testing on my case takes 2 min and painting 28 min.

The time seems to be spent between the "Starting copy source file..." and "Copied ...".
Unfortunately I don't know how to prepare a test setup to profile this code, which makes understanding where is the time spent difficult.

**Comment by mheinzerling** [comment]
We have the same issue with 900 files and 5 minutes, too. Didn't had time to investigate it yet in detail.
Is this network related by sending files individually to the master or is the painting itself slow? In both cases it seems reasonable to parallelize the process?

**Comment by sratz** [comment]
We are seeing the same:

```
Publishing Coverage report....
A total of 1 reports were found
Source File Navigation is enabled - Current level: STORE_LAST_BUILD
15579 source files need to be copied.
...
```
Each file takes about 5 seconds to be copied which makes this impossible to use.

**Comment by uhafner** [comment]
It would be helpful if someone of the reporters can look into this issue as the plugin currently has no active maintainers.

**Comment by uhafner** [comment]
An improved  implementation is available in #265. if someone wants to test, please let me know…

**Comment by mheinzerling** [comment]
#265 was not merged, was it? The issue seems do still exists with Prism 1.26.0-2 and Coverage 2.0.4. How can I help you here?

`
00:06:53.750  Source File Navigation is enabled - Current level: STORE_LAST_BUILD
00:06:53.750  1280 source files need to be copied.
00:06:54.343  Starting copy source file X.java. 
00:06:54.603  Copied X.java. 
...
00:11:45.912  Starting copy source file Y.java. 
00:11:46.122  Copied Y.java. 
`

**Comment by uhafner** [comment]
The issue has been merged but is not yet released. Since I needed to add new parameters to the pipeline I thought it would makes sense to release a 3.0.0 version with the delta coverage changes from https://github.com/jenkinsci/code-coverage-api-plugin/pull/324 as well. But maybe a intermediate release would make sense as well.

**Comment by mheinzerling** [comment]
If we are talking about weeks or some months, there is no need do hurry from my point of view. This issue is just blocking us from migrating everything to this plugin and drop the jacoco-plugin completely. Do whatever fits your rare available time best.
