### ISSUE TITLE
Missing example of coverage thresholds for pipeline syntax

### ISSUE THREAD

**Issue by Thogor** [jenkinsci/code-coverage-api-plugin#72]
I'm trying to add coverage thresholds through the pipeline syntax as described in [https://jenkins.io/doc/pipeline/steps/code-coverage-api/](url). 

My experience in Groovy is limited and I've tried the following: 

`publishCoverage(adapters: [istanbulCoberturaAdapter(path: 'coverage/part66/cobertura-coverage.xml')], globalThresholds: [threshold(thresholdTarget: '100')])
`

This results in java.lang.NoSuchMethodError: No such DSL method 'threshold' found among steps etc.

`publishCoverage adapters: [istanbulCoberturaAdapter(path: 'coverage/part66/cobertura-coverage.xml')], globalThresholds: [thresholdTarget: '100', unstableThreshold: '100']
`

This results in java.lang.UnsupportedOperationException: must specify $class with an implementation of interface java.util.List. 

`publishCoverage(adapters: [istanbulCoberturaAdapter(path: 'coverage/part66/cobertura-coverage.xml')], globalThresholds: [$class: 'Threshold', thresholdTarget: '100'])
`

This results in java.lang.UnsupportedOperationException: no known implementation of interface java.util.List is named Threshold. 

It would be very helpful if there was an example of the correct usage of the globalThresholds argument in the documentation concerning the pipeline syntax. 

Any help will be appreciated and thank you for making this plugin :)

**Comment by cizezsy** [comment]
@Thogor If you have a Pipeline job in Jenkins, you can see a link named 'Pipeline Syntax' at the side panel.

<img width="200" alt="WeChata460e493ec78012458258394fc88da40" src="https://user-images.githubusercontent.com/22002278/54591575-7c5af980-4a65-11e9-82a1-1c15e111b7e1.png">

In there, you can found the publishCoverage step
<img width="2098" alt="WeChat1055734dc3ea3f8ccd1494a57cd5d8a1" src="https://user-images.githubusercontent.com/22002278/54591823-06a35d80-4a66-11e9-8767-7417485972a6.png">

Then, you can config plugin on UI and generate the corresponding pipeline snippet :P
![image](https://user-images.githubusercontent.com/22002278/54591958-4c602600-4a66-11e9-8aa0-9c6eeb1a7799.png)

```groovy
publishCoverage adapters: [istanbulCoberturaAdapter(path: 'coverage/part66/cobertura-coverage.xml', thresholds: [[thresholdTarget: 'Function', unhealthyThreshold: 80.0, unstableThreshold: 100.0]])], sourceFileResolver: sourceFiles('NEVER_STORE')
```

**Note**: I do not suggest you config threshold at the global level, because it will list all threshold types(Not just JavaScript but also include Java and other languages, I will improve it in next version). It is hard to find the correct one. But if you upgrade the plugin to 1.0.8, you can see the filtered threshold types in adapter level. It is much easier to use :)

**Comment by Thogor** [comment]
I've found Snippet generator and will define the thresholds on the level of my coverage adapter instead of using the globalThresholds. 

Thank you for the help!

**Comment by y0y0z** [comment]
> I've found Snippet generator and will define the thresholds on the level of my coverage adapter instead of using the globalThresholds.
> 
> Thank you for the help!

@Thogor: i am interested in it, would you please share a snippet or a reference?

**Comment by tempora-mutantur** [comment]
@y0y0z 

An example is mentioned in this comment:
